### ISSUE TITLE
Wrong python3 implementation

### ISSUE THREAD

**Issue by michal-pasternak** [nikhilkumarsingh/PyOBEX3#1]
Hello, I installed PyOBEX with pip3 manager. Library works fine only for Python 2.

```
#!/usr/bin/env python3
from PyOBEX import client, headers, responses
```

Traceback:

> Traceback (most recent call last):
>   File "contacts_2.py", line 4, in <module>
>     from PyOBEX import client, headers, responses
>   File "/usr/local/lib/python3.7/dist-packages/PyOBEX/client.py", line 489, in <module>
>     class SyncClient(Client):
>   File "/usr/local/lib/python3.7/dist-packages/PyOBEX/client.py", line 491, in SyncClient
>     def connect(self, header_list = (headers.Target("IRMC-SYNC"),)):
>   File "/usr/local/lib/python3.7/dist-packages/PyOBEX/headers.py", line 33, in __init__
>     self.data = self.encode(data)
>   File "/usr/local/lib/python3.7/dist-packages/PyOBEX/headers.py", line 50, in encode
>     return struct.pack(">BH", self.code, len(data) + 3) + data
> TypeError: can't concat str to bytes

**Comment by kratz00** [comment]
@mic327 Better late than never, give the upstream project a chance https://gitlab.com/dboddie/pyobex/-/tree/python3
